query GetEventNftCollectionByContractAddressWithMinimalEventPasses(
  $contractAddress: String!
  $stage: Stage!
) {
  eventNftCollection_by_pk(contractAddress: $contractAddress) {
    activityWebhookId
    chainId
    contractAddress
    eventPass {
      event {
        organizer {
          id
        }
      }
    }
  }
}

fragment EventNftCollectionFields on eventNftCollection {
  contractAddress
  chainId
  eventPassId
  activityWebhookId
}

mutation CreateEventNftCollection($object: eventNftCollection_insert_input!) {
  insert_eventNftCollection_one(object: $object) {
    ...EventNftCollectionFields
  }
}

#mutation UpsertEventPassOrders($objects: [eventPassOrder_insert_input!]!) {
#  insert_eventPassOrder(
#    objects: $objects
#    on_conflict: { constraint: eventPassOrder_pkey, update_columns: [quantity] }
#  ) {
#    returning {
#      id
#      quantity
#      status
#      eventPassId
#      accountId
#      created_at
#    }
#  }
#}
