query GetEvent($slug: String!, $locale: Locale!, $stage: Stage!) @cached {
  event(where: { slug: $slug }, locales: [$locale, en], stage: $stage) {
    ...EventListFields
    description {
      json
      references {
        ... on Asset {
          __typename
          id
          url
          mimeType
        }
      }
    }
    organizer {
      id
      slug
      name
      image {
        url
      }
    }
    eventDateLocations {
      ...EventDateLocationsFields
    }
  }
}

query GetEventWithPasses($slug: String!, $locale: Locale!, $stage: Stage!)
@cached {
  event(where: { slug: $slug }, locales: [$locale, en], stage: $stage) {
    id
    slug
    title
    heroImage {
      url
    }
    organizer {
      id
      slug
      name
      image {
        url
      }
    }
    eventDateLocations {
      ...EventDateLocationsFields
    }
    eventPasses {
      id
      name
      description
      eventPassPricing {
        priceAmount
        priceCurrency
        maxAmount
        maxAmountPerUser
      }
    }
  }
}

query GetEventsFromOrganizerIdTable($id: ID!, $locale: Locale!, $stage: Stage!)
@cached {
  organizer(where: { id: $id }, locales: [$locale, en], stage: $stage) {
    events {
      title
      slug
      eventParameters {
        dateStart
        dateEnd
        dateSaleStart
        dateSaleEnd
        timezone
      }
    }
  }
}

query GetEventWithPassesOrganizer(
  $slug: String!
  $locale: Locale!
  $stage: Stage!
) @cached {
  event(where: { slug: $slug }, locales: [$locale, en], stage: $stage) {
    title
    id
    slug
    heroImage {
      url
    }
    eventPasses {
      name
      id
      description
      nftName
      nftImage {
        url
      }
      nftDescription
      eventPassPricing {
        maxAmount
        maxAmountPerUser
        priceAmount
        priceCurrency
      }
      eventPassNftContract {
        contractAddress
      }
    }
  }
}
