mutation CreateEventPassPricing(
  $eventPassPricing: eventPassPricing_insert_input!
) {
  insert_eventPassPricing_one(object: $eventPassPricing) {
    id
    eventPassId
    priceAmount
    priceCurrency
    maxAmount
    maxAmountPerUser
  }
}

mutation UpdateEventPassPricing(
  $id: uuid!
  $eventPassPricing: eventPassPricing_set_input!
) {
  update_eventPassPricing_by_pk(
    pk_columns: { id: $id }
    _set: $eventPassPricing
  ) {
    id
    eventPassId
    priceAmount
    priceCurrency
    maxAmount
    maxAmountPerUser
  }
}
