query GetEventNftCollectionByContractAddressWithMinimalEventPasses(
  $contractAddress: String!
  $stage: Stage!
) {
  eventNftCollection_by_pk(contractAddress: $contractAddress) {
    activityWebhookId
    chainId
    contractAddress
    eventPass {
      event {
        organizer {
          id
        }
      }
    }
  }
}
