version: '3.9'

services:
  frontend:
    build:
      context: frontend
      dockerfile: frontend.dockerfile.local
    restart: always
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  
  django:
    build: ./backend/django
    container_name: backend-django
    # restart: always
    stdin_open: true
    tty: true
    depends_on:
      - 'postgres'
    volumes:
      - ./backend/django:/backend
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SECRET: 'Q3d5ymmEjNBw37XQdL4xeRVvDCxgvqFrisALR4bng-0' # *** CHANGE THIS ***
    ports:
      - "8000:8000"
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'password'

  hasura:
    image: hasura/graphql-engine:latest.cli-migrations-v2
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    container_name: hasura
    restart: always
    depends_on:
      - 'postgres'
      - 'django'
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:password@postgres:5432/postgres'
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "Q3d5ymmEjNBw37XQdL4xeRVvDCxgvqFrisALR4bng-0" }' # *** CHANGE THIS ***
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: password
      REMOTE_SCHEMA_ENDPOINT: http://host.docker.internal:8000/graphql
    ports:
      - "127.0.0.1:8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"