version: '3.9'

services:

  # svelte:
  #   image: node:lts
  #   container_name: client-svelte
  #   restart: unless-stopped
  #   command: bash -c "npm install && HOST=0.0.0.0 npm run dev"
  #   ports:
  #     - "127.0.0.1:35729:35729" # Live Reload
  #     - "127.0.0.1:8088:8088"
  #   working_dir: /home/node/apps/app
  #   volumes:
  #     - ./clients/svelte:/home/node/apps/app
  frontend-client:
    build:
      context: frontend/client
      dockerfile: Dockerfile.frontend-client.local
    restart: unless-stopped
    ports:
      - 3000:3000
      - 24678:24678
    command: /bin/sh -c "npm run dev"
    volumes:
      - ./frontend/client:/frontend
      - client_node_modules:/frontend/node_modules
      - client_dotnuxt:/frontend/.nuxt
  
  backend-django:
    build: 
      context: backend/django
      dockerfile: Dockerfile.backend-django.local
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - 'postgres'
    volumes:
      - ./backend/django:/backend
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SECRET: 'Q3d5ymmEjNBw37XQdL4xeRVvDCxgvqFrisALR4bng-0' # *** CHANGE THIS ***
    ports:
      - "8000:8000"
  postgres:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend-hasura:
    image: hasura/graphql-engine:latest
    volumes:
      - ./backend/hasura:/hasura
    container_name: governance_backend_hasura
    restart: unless-stopped
    depends_on:
      - 'postgres'
    environment:
      # enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # this "console" does not save migrations, we need the "hasura-cli console" for that.
      # enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:password@postgres:5432/postgres'
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "Q3d5ymmEjNBw37XQdL4xeRVvDCxgvqFrisALR4bng-0" }' # *** CHANGE THIS ***
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: password
    ports:
      - "8080:8080"
      - "9695:9695"
      - "9693:9693"
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  db_data:
  client_node_modules:
  client_dotnuxt: