query GetAlchemyInfosFromEventId($eventId: String) {
  eventParameters(where: { eventId: { _eq: $eventId } }) {
    activityWebhookId
    signingKey
  }
}

query GetEventParameters($eventId: String) {
  eventParameters(where: { eventId: { _eq: $eventId } }) {
    dateStart
    dateEnd
    dateSaleStart
    dateSaleEnd
    timezone
    status
    isSaleOngoing
    isOngoing
  }
}
