query GetSigningKeyFromEventId($eventId: String) {
  eventParameters(where: { eventId: { _eq: $eventId } }) {
    signingKey
  }
}

mutation InsertEventParameters($objects: [eventParameters_insert_input!]!) {
  insert_eventParameters(objects: $objects) {
    returning {
      id
      activityWebhookId
      eventId
    }
  }
}
