mutation UpdateUser($id: uuid!, $user: users_set_input!) {
  update_users_by_pk(_set: $user, pk_columns: { id: $id }) {
    ...UserFields
  }
}
mutation CreateUser($user: users_insert_input!) {
  insert_users_one(object: $user) {
    ...UserFields
  }
}

query GetUser($address: String!) {
  users(where: { address: { _eq: $address } }) {
    ...UserFields
  }
}

query GetUserByEmail($email: String!) {
  users(where: { email: { _eq: $email } }) {
    ...UserFields
  }
}
