query GetContractAddressFromEventPassId($eventPassId: String) @cached {
  eventPassNftContract(where: { eventPassId: { _eq: $eventPassId } }) {
    contractAddress
  }
}

query GetEventPassNftContractDelayedRevealedFromEventPassId(
  $eventPassId: String
) @cached {
  eventPassNftContract(where: { eventPassId: { _eq: $eventPassId } }) {
    type
    isDelayedRevealed
  }
}

query GetEventPassNftContractDelayedRevealPassword($contractAddress: String)
@cached {
  eventPassNftContract(where: { contractAddress: { _eq: $contractAddress } }) {
    type
    isDelayedRevealed
    password
  }
}

query GetEventPassNftContractNftsLazyMinted($eventPassId: String) @cached {
  eventPassNftContract(where: { eventPassId: { _eq: $eventPassId } }) {
    contractAddress
    eventPassId
    eventPassNfts(where: { status: { _eq: LAZY_MINTED } }) {
      id
      packId
      currentOwnerAddress
      contractAddress
      eventId
      tokenId
      eventPassId
      status
    }
  }
}
