mutation CreateEventPassNftContract(
  $object: eventPassNftContract_insert_input!
) {
  insert_eventPassNftContract_one(object: $object) {
    chainId
    contractAddress
    eventId
    eventPassId
    organizerId
  }
}
