query GetEventPasses($eventSlug: String!, $locale: Locale!, $stage: Stage!)
@cached {
  eventPasses(
    where: { event: { slug: $eventSlug } }
    locales: [$locale, en]
    stage: $stage
  ) {
    id
    name
    description
    nftImage {
      url
    }
    passAmount {
      ...PassAmountFields
    }
    passPricing {
      ...PassPricingFields
    }
    passOptions {
      name
      description
      eventDateLocation {
        ...EventDateLocationsFields
      }
    }
    eventPassNftContract {
      type
      isDelayedRevealed
    }
  }
}

query GetEventPassDelayedRevealedFromEventPassId(
  $eventPassId: ID!
  $locale: Locale!
  $stage: Stage!
) @cached {
  eventPass(
    where: { id: $eventPassId }
    locales: [$locale, en]
    stage: $stage
  ) {
    eventPassDelayedRevealed {
      name
      description
      nftName
      nftDescription
      nftImage {
        url
      }
      passOptions {
        name
        description
        eventDateLocation {
          ...EventDateLocationsFields
        }
      }
    }
  }
}
