query GetContractAddressFromEventPassId($eventPassId: String) @cached {
  eventPassNftContract(where: { eventPassId: { _eq: $eventPassId } }) {
    contractAddress
  }
}

query GetEventPassNftContractDelayedRevealedFromEventPassId(
  $eventPassId: String
) @cached {
  eventPassNftContract(where: { eventPassId: { _eq: $eventPassId } }) {
    type
    isDelayedRevealed
  }
}
