query GetEventPasses($eventSlug: String!, $locale: Locale!, $stage: Stage!)
@cached {
  eventPasses(
    where: { event: { slug: $eventSlug } }
    locales: [$locale, en]
    stage: $stage
  ) {
    id
    name
    description
    nftImage {
      url
    }
    eventPassPricing {
      maxAmount
      maxAmountPerUser
      priceAmount
      priceCurrency
    }
    passOptions {
      name
      description
      eventDateLocation {
        ...EventDateLocationsFields
      }
    }
  }
}
