mutation CreatePackNftContract($object: packNftContract_insert_input!) {
  insert_packNftContract_one(object: $object) {
    id
    chainId
    contractAddress
    organizerId
    rewardsPerPack
    packId
  }
}
