query GetPackNftContractFromPackId($packId: String) @cached {
  packNftContract(where: { packId: { _eq: $packId } }) {
    id
    chainId
    rewardsPerPack
    organizerId
    contractAddress
    eventPassNftContracts {
      eventPassNftContractId
      amount
    }
    eventPassNfts {
      tokenId
      contractAddress
      currentOwnerAddress
      eventPassId
      packId
    }
  }
}
