query GetPackNftContractFromPackId($packId: String) @cached {
  packNftContract(where: { packId: { _eq: $packId } }) {
    id
    chainId
    rewardsPerPack
    organizerId
    contractAddress
    eventPassIds
    eventPassNfts {
      tokenId
      contractAddress
      currentOwnerAddress
      eventPassId
      packId
    }
  }
}
