query GetPackNftSupplyWithNullNftsFromCurrentOwnerAddress(
  $contractAddress: String!
  $currentOwnerAddress: String!
) {
  packNftSupply(
    where: {
      redeemableNfts: { _is_null: true }
      eventPassNfts: { _is_null: true }
      contractAddress: { _eq: $contractAddress }
      currentOwnerAddress: { _eq: $currentOwnerAddress }
    }
  ) {
    id
    organizerId
  }
}
