query GetEventPassOrdersConfirmed {
  eventPassOrder(where: { status: { _eq: CONFIRMED } }) {
    eventPassId
    quantity
  }
}

query GetEventPassOrdersFromIds($eventPassOrderIds: [uuid!]!, $stage: Stage!) {
  eventPassOrder(where: { id: { _in: $eventPassOrderIds } }) {
    eventPassId
    quantity
    eventPass(locales: [en], stage: $stage) {
      event {
        slug
        organizer {
          slug
        }
      }
    }
  }
}

query GetEventPassOrderPurchasedForEventPassesId($eventPassId: String!) {
  eventPassOrder(
    where: {
      status: { _in: [CONFIRMED, COMPLETED, IS_MINTING] }
      eventPassId: { _eq: $eventPassId }
    }
  ) {
    eventPassId
    quantity
  }
}

query GetEventPassOrderPurchasedForEventPassesIds($eventPassIds: [String!]!) {
  eventPassOrder(
    where: {
      status: { _in: [CONFIRMED, COMPLETED, IS_MINTING] }
      eventPassId: { _in: $eventPassIds }
    }
  ) {
    eventPassId
    quantity
  }
}
