query GetEventWithPasses($slug: String!, $locale: Locale!, $stage: Stage!)
@cached {
  event(where: { slug: $slug }, locales: [$locale, en], stage: $stage) {
    id
    slug
    title
    heroImage {
      url
    }
    heroImageClasses
    organizer {
      id
      slug
      name
      image {
        url
      }
      imageClasses
    }
    eventPasses {
      id
      name
      description
      passPricing {
        ...PassPricingFields
      }
      passAmount {
        ...PassAmountFields
      }
    }
  }
}
