query GetEventPassPendingOrderForEventPasses($eventPassIds: [String!]) {
  eventPassPendingOrder(where: { eventPassId: { _in: $eventPassIds } }) {
    id
    eventPassId
    quantity
    created_at
  }
}

query GetEventPassPendingOrders($locale: Locale!, $stage: Stage!) {
  eventPassPendingOrder {
    id
    eventPassId
    quantity
    created_at
    eventPass(locales: [$locale, en], stage: $stage) {
      event {
        slug
        organizer {
          slug
        }
      }
    }
  }
}

query GetEventPassPendingOrdersMinimal {
  eventPassPendingOrder {
    eventPassId
    quantity
  }
}
