query GetEventPassOrdersConfirmed {
  eventPassOrder(where: { status: { _eq: CONFIRMED } }) {
    eventPassId
    quantity
  }
}

query GetEventPassOrdersConfirmedOrCompletedForEventPassIds(
  $eventPassIds: [String!]!
) {
  eventPassOrder(
    where: {
      status: { _in: [CONFIRMED, COMPLETED] }
      eventPassId: { _in: $eventPassIds }
    }
  ) {
    eventPassId
    quantity
  }
}
