query GetEventWithPasses($slug: String!, $locale: Locale!, $stage: Stage!)
@cached {
  event(where: { slug: $slug }, locales: [$locale, en], stage: $stage) {
    id
    slug
    title
    heroImage {
      url
    }
    organizer {
      id
      slug
      name
      image {
        url
      }
    }
    eventPasses {
      id
      name
      description
      eventPassPricing {
        priceAmount
        priceCurrency
      }
    }
  }
}
