query GetSecretApiKey($apiKey: String!) {
  secretApiKey(where: { apiKey: { _eq: $apiKey } }) {
    id
    hashedOriginSecret
    originSecretSalt
    encryptedIntegritySecret
    allowlist
    organizerId
    expiresAt
    status
    type
  }
}
