mutation CreateSecretApiKey($object: secretApiKey_insert_input!) {
  insert_secretApiKey_one(object: $object) {
    id
    name
    apiKey
    hashedOriginSecret
    originSecretSalt
    encryptedIntegritySecret
    allowlist
    organizerId
    expiresAt
    type
  }
}

mutation UpdateSecretApiKey(
  $id: uuid!
  $allowlist: String
  $expiresAt: timestamptz
  $status: apiKeyStatus_enum
) {
  update_secretApiKey_by_pk(
    pk_columns: { id: $id }
    _set: { allowlist: $allowlist, expiresAt: $expiresAt, status: $status }
  ) {
    name
    hashedOriginSecret
    originSecretSalt
    encryptedIntegritySecret
    allowlist
    organizerId
    expiresAt
  }
}
