query GetEventPassPendingOrderForEventPass($eventPassId: String!) {
  eventPassPendingOrder(where: { eventPassId: { _eq: $eventPassId } }) {
    id
    eventPassId
    quantity
    created_at
  }
}

query GetEventPassPendingOrderForEventPasses($eventPassIds: [String!]) {
  eventPassPendingOrder(where: { eventPassId: { _in: $eventPassIds } }) {
    id
    eventPassId
    quantity
    created_at
  }
}

query GetEventPassPendingOrders($stage: Stage!) {
  eventPassPendingOrder {
    id
    eventPassId
    quantity
    created_at
    eventPassPricing {
      timeBeforeDelete
    }
    eventPass(locales: [en], stage: $stage) {
      event {
        slug
        organizer {
          slug
        }
      }
    }
  }
}

query GetEventPassPendingOrdersMinimal {
  eventPassPendingOrder {
    eventPassId
    quantity
  }
}
