-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP TRIGGER eventPassOrder_trigger ON "eventPassOrder";
-- DROP TRIGGER eventPassPendingOrder_trigger ON "eventPassPendingOrder";
-- DROP FUNCTION check_event_pass_order();
