query GetAccountEventPassOrderForEventPasses(
  $accountId: uuid!
  $eventPassIds: [String!]
) {
  eventPassOrder(
    where: {
      accountId: { _eq: $accountId }
      eventPassId: { _in: $eventPassIds }
    }
  ) {
    eventPassId
    quantity
    status
    created_at
  }
}

mutation UpsertEventPassOrders($objects: [eventPassOrder_insert_input!]!) {
  insert_eventPassOrder(
    objects: $objects
    on_conflict: { constraint: eventPassOrder_pkey, update_columns: [quantity] }
  ) {
    returning {
      id
      quantity
      status
      eventPassId
      accountId
      created_at
    }
  }
}
