query GetAccountEventPassOrderForEventPasses(
  $accountId: uuid!
  $eventPassIds: [String!]
) {
  eventPassOrder(
    where: {
      accountId: { _eq: $accountId }
      eventPassId: { _in: $eventPassIds }
    }
  ) {
    eventPassId
    quantity
    status
    created_at
  }
}

query GetEventPassOrderFromId($id: uuid!) {
  eventPassOrder_by_pk(id: $id) {
    id
    eventPassId
    quantity
    status
    eventPassNftContract {
      contractAddress
    }
    account {
      address
    }
    eventPassPricing {
      priceAmount
    }
  }
}

query GetEventPassOrdersFromStripeCheckoutSession(
  $stripeCheckoutSessionId: String!
) {
  eventPassOrder(
    where: { stripeCheckoutSessionId: { _eq: $stripeCheckoutSessionId } }
  ) {
    id
    eventPassId
    quantity
    status
    eventPassNftContract {
      contractAddress
    }
    account {
      address
    }
    eventPassPricing {
      priceAmount
    }
  }
}
