query GetEventPassPendingOrders {
  eventPassPendingOrder {
    created_at
    id
    eventPassId
    account {
      email
      address
    }
    eventPassPricing {
      timeBeforeDelete
    }
  }
}

mutation DeleteEventPassPendingOrders($ids: [uuid!]!) {
  delete_eventPassPendingOrder(where: { id: { _in: $ids } }) {
    affected_rows
  }
}
