query GetAccountEventPassOrderForEventPasses(
  $accountId: uuid!
  $eventPassIds: [String!]
) {
  eventPassOrder(
    where: {
      accountId: { _eq: $accountId }
      eventPassId: { _in: $eventPassIds }
    }
  ) {
    eventPassId
    quantity
    status
    created_at
  }
}

query GetEventPassOrdersFromStripeCheckoutSession(
  $stripeCheckoutSessionId: String!
) {
  eventPassOrder(
    where: { stripeCheckoutSessionId: { _eq: $stripeCheckoutSessionId } }
  ) {
    id
    eventPassId
    quantity
    status
    eventPassNftContract {
      contractAddress
    }
    account {
      address
    }
  }
}
