query GetEventPassPendingOrders {
  eventPassPendingOrder {
    created_at
    id
    eventPassId
    account {
      email
      address
    }
    eventPassPricing {
      timeBeforeDelete
    }
  }
}
