query GetAccountEventPassOrderForEventPasses(
  $accountId: uuid!
  $eventPassIds: [String!]
) {
  eventPassOrder(
    where: {
      accountId: { _eq: $accountId }
      eventPassId: { _in: $eventPassIds }
    }
  ) {
    eventPassId
    quantity
    status
    created_at
  }
}
