mutation UpdateOrdersStatus($updates: [order_updates!]!) {
  update_order_many(updates: $updates) {
    affected_rows
    returning {
      id
      quantity
      status
      eventPassId
      packId
      accountId
      created_at
    }
  }
}

mutation SetOrdersStripeCheckoutSessionId($updates: [order_updates!]!) {
  update_order_many(updates: $updates) {
    affected_rows
    returning {
      id
      quantity
      status
      eventPassId
      packId
      accountId
      created_at
      stripeCheckoutSessionId
    }
  }
}

mutation MovePendingOrdersToConfirmed(
  $pendingOrdersIds: [uuid!]!
  $objects: [order_insert_input!]!
  $locale: Locale!
  $stage: Stage!
) {
  delete_pendingOrder(where: { id: { _in: $pendingOrdersIds } }) {
    affected_rows
  }
  insert_order(objects: $objects) {
    returning {
      id
      quantity
      status
      eventPassId
      packId
      accountId
      created_at
      passPricing {
        amount
        currency
      }
      eventPass(locales: [$locale, en], stage: $stage) {
        id
        name
        nftImage {
          url
        }
        event {
          slug
          organizer {
            slug
          }
        }
      }
    }
  }
}
