query GetPendingOrders {
  pendingOrder {
    created_at
    id
    eventPassId
    packId
    account {
      address
    }
    passAmount {
      timeBeforeDelete
    }
    packAmount {
      timeBeforeDelete
    }
  }
}
