-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."eventPassOrder" add column "stripeCheckoutSessionId" text
--  null;
