query GetOrganizer($slug: String!, $locale: Locale!, $stage: Stage!) @cached {
  organizer(where: { slug: $slug }, locales: [$locale, en], stage: $stage) {
    ...OrganizerFields
  }
}

query GetOrganizerFromId($id: ID!, $stage: Stage!) @cached {
  organizer(where: { id: $id }, stage: $stage) {
    ...OrganizerFields
  }
}
