query GetOrganizer($slug: String!, $locale: Locale!, $stage: Stage!) @cached {
  organizer(where: { slug: $slug }, locales: [$locale, en], stage: $stage) {
    ...OrganizerFields
  }
}

query GetAllOrganizerSlugsWithEventsSlugs {
  organizers(stage: DRAFT) {
    slug
    events {
      slug
    }
  }
}
