query GetContentSpaceFromOrganizerIdTable(
  $id: ID!
  $locale: Locale!
  $stage: Stage!
) @cached {
  organizer(where: { id: $id }, locales: [$locale, en], stage: $stage) {
    contentSpaces {
      slug
      title
      contentSpaceParameters {
        status
      }
    }
  }
}

query GetContentSpaceWithEventPassesOrganizer(
  $slug: String!
  $locale: Locale!
  $stage: Stage!
) @cached {
  contentSpace(where: { slug: $slug }, locales: [$locale, en], stage: $stage) {
    title
    slug
    heroImage {
      url
    }
    contentSpaceParameters {
      status
    }
    eventPasses(forceParentLocale: true) {
      ... on EventPass {
        id
        name
        event {
          slug
          title
        }
      }
    }
  }
}
