mutation UpsertNftTransfer($objects: [nftTransfer_insert_input!]!) {
  insert_nftTransfer(
    objects: $objects
    on_conflict: {
      constraint: nft_transfer_unique_transfer
      update_columns: []
    }
  ) {
    affected_rows
    returning {
      ...NftTransferFields
    }
  }
}
