// @ts-check
import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

const env = createEnv({
  client: {
    NEXT_PUBLIC_APP: z.string().optional(),
    NEXT_PUBLIC_THIRDWEB_CLIENT_ID: z.string().min(1),
    NEXT_PUBLIC_HYGRAPH_STAGE: z.string().min(1),
    NEXT_PUBLIC_HASURA_PROJECT_ENDPOINT: z.string().url(),
    NEXT_PUBLIC_WEB3AUTH_CLIENT_ID: z.string().min(1),
    NEXT_PUBLIC_WEB3AUTH_NETWORK: z.string().min(1),
    NEXT_PUBLIC_WEB3AUTH_SESSION_TIME: z.string().min(1),
    NEXT_PUBLIC_CHAIN: z.string().min(1),
    NEXT_PUBLIC_ALCHEMY_API_KEY: z.string().min(1),
    NEXT_PUBLIC_UPLOAD_ACCOUNT_ID: z.string().min(1),
    NEXT_PUBLIC_UPLOAD_PATH_PREFIX: z.string().min(1),
    NEXT_PUBLIC_UPLOAD_PUBLIC_API_KEY: z.string().min(1),
    NEXT_PUBLIC_SENTRY_DSN: z.string().url().optional(),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().min(1),
    NEXT_PUBLIC_OPENZEPPELIN_URL: z.string().min(1),
    NEXT_PUBLIC_THIRDWEB_MASTER_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_POSTHOG_KEY: z.string().min(1),
  },
  runtimeEnv: {
    NEXT_PUBLIC_APP: process.env.NEXT_PUBLIC_APP,
    NEXT_PUBLIC_THIRDWEB_CLIENT_ID: process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID,
    NEXT_PUBLIC_HYGRAPH_STAGE: process.env.NEXT_PUBLIC_HYGRAPH_STAGE,
    NEXT_PUBLIC_HASURA_PROJECT_ENDPOINT:
      process.env.NEXT_PUBLIC_HASURA_PROJECT_ENDPOINT,
    NEXT_PUBLIC_WEB3AUTH_CLIENT_ID: process.env.NEXT_PUBLIC_WEB3AUTH_CLIENT_ID,
    NEXT_PUBLIC_WEB3AUTH_NETWORK: process.env.NEXT_PUBLIC_WEB3AUTH_NETWORK,
    NEXT_PUBLIC_WEB3AUTH_SESSION_TIME:
      process.env.NEXT_PUBLIC_WEB3AUTH_SESSION_TIME,
    NEXT_PUBLIC_CHAIN: process.env.NEXT_PUBLIC_CHAIN,
    NEXT_PUBLIC_ALCHEMY_API_KEY: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY,
    NEXT_PUBLIC_UPLOAD_ACCOUNT_ID: process.env.NEXT_PUBLIC_UPLOAD_ACCOUNT_ID,
    NEXT_PUBLIC_UPLOAD_PATH_PREFIX: process.env.NEXT_PUBLIC_UPLOAD_PATH_PREFIX,
    NEXT_PUBLIC_UPLOAD_PUBLIC_API_KEY:
      process.env.NEXT_PUBLIC_UPLOAD_PUBLIC_API_KEY,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_OPENZEPPELIN_URL: process.env.NEXT_PUBLIC_OPENZEPPELIN_URL,
    NEXT_PUBLIC_THIRDWEB_MASTER_ADDRESS:
      process.env.NEXT_PUBLIC_THIRDWEB_MASTER_ADDRESS,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
  },
});

export default env;
