query GetPassedEventsWithEventPassNfts(
  $address: String!
  $currentDate: timestamp!
  $locale: Locale!
  $stage: Stage!
) {
  eventParameters(
    where: {
      eventPassNfts: { currentOwnerAddress: { _ilike: $address } }
      dateEnd: { _lt: $currentDate }
      status: { _eq: PUBLISHED }
    }
    order_by: { dateEnd: desc }
  ) {
    dateStart
    dateEnd
    timezone
    eventPassNftContracts(
      where: { eventPassNfts: { currentOwnerAddress: { _ilike: $address } } }
    ) {
      type
      isDelayedRevealed
      eventPass(locales: [$locale, en], stage: $stage) {
        id
        name
        event {
          slug
        }
        nftImage {
          url
        }
      }
      eventPassNfts(where: { currentOwnerAddress: { _ilike: $address } }) {
        id
        isRevealed
        tokenId
      }
    }
    organizer(where: {}, locales: [$locale, en], stage: $stage) {
      id
      slug
      name
      image {
        url
      }
      imageClasses
    }
    event(where: {}, locales: [$locale, en], stage: $stage) {
      id
      slug
      title
      heroImage {
        url
      }
      heroImageClasses
    }
  }
}

query GetUpcomingEventsWithEventPassNfts(
  $address: String!
  $currentDate: timestamp!
  $locale: Locale!
  $stage: Stage!
) {
  eventParameters(
    where: {
      eventPassNfts: { currentOwnerAddress: { _ilike: $address } }
      dateEnd: { _gte: $currentDate }
      status: { _eq: PUBLISHED }
    }
    order_by: { dateStart: asc }
  ) {
    dateStart
    dateEnd
    timezone
    eventPassNftContracts(
      where: { eventPassNfts: { currentOwnerAddress: { _ilike: $address } } }
    ) {
      type
      isDelayedRevealed
      eventPass(locales: [$locale, en], stage: $stage) {
        id
        name
        event {
          slug
        }
        nftImage {
          url
        }
      }
      eventPassNfts(where: { currentOwnerAddress: { _ilike: $address } }) {
        id
        isRevealed
        tokenId
      }
    }
    organizer(where: {}, locales: [$locale, en], stage: $stage) {
      id
      slug
      name
      image {
        url
      }
      imageClasses
    }
    event(where: {}, locales: [$locale, en], stage: $stage) {
      id
      slug
      title
      heroImage {
        url
      }
      heroImageClasses
    }
  }
}
