query GetEventPassNftById($id: uuid!, $locale: Locale!, $stage: Stage!)
@cached {
  eventPassNft_by_pk(id: $id) {
    ...EventPassNftFields
    eventPass(locales: [$locale, en], stage: $stage) {
      name
      nftImage {
        url
      }
      description
      passOptions {
        name
        description
        eventDateLocation {
          ...EventDateLocationsFields
        }
      }
      eventPassPricing {
        priceAmount
        priceCurrency
      }
      event {
        title
        slug
        heroImage {
          url
        }
        description {
          json
          references {
            ... on Asset {
              __typename
              id
              url
              mimeType
            }
          }
        }
        organizer {
          slug
          name
          image {
            url
          }
        }
      }
    }
  }
}
