schema: ${HASURA_PROJECT_ENDPOINT}
extensions:
  codegen:
    generates:
      ./src/types.ts:
        plugins:
          - typescript
          - typescript-resolvers
          - typescript-operations
          - typescript-vue-apollo