query getAccount($address: String!) {
  account(where: { address: { _eq: $address } }) {
    ...AccountFields
  }
}

query getAccountByEmail($email: String!) {
  account(where: { email: { _eq: $email } }) {
    ...AccountFields
  }
}
