query getUser($address: String!) {
  users(where: { address: { _eq: $address } }) {
    ...UserFields
  }
}

query getUserByEmail($email: String!) {
  users(where: { email: { _eq: $email } }) {
    ...UserFields
  }
}
