// @ts-check
import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

const env = createEnv({
  server: {
    NX_CLOUD_AUTH_TOKEN: z.string().min(1),
    NX_CACHE_DIRECTORY: z.string().min(1),
    HASURA_VERSION: z.string().min(1),
    HASURA_GRAPHQL_SERVER_PORT: z.coerce.number(),
    HASURA_GRAPHQL_ADMIN_SECRET: z.string().min(1),
    HASURA_CONSOLE_PORT: z.coerce.number(),
    HASURA_GRAPHQL_DATABASE_URL: z.string().url(),
    HYGRAPH_CMS_WEBHOOK_READ_URL: z.string().url(),
    HASURA_GRAPHQL_UNAUTHORIZED_ROLE: z.string().min(1),
    POSTGRES_USER: z.string().min(1),
    POSTGRES_DB: z.string().min(1),
    POSTGRES_PASSWORD: z.string().min(1),
    POSTGRES_PORT: z.coerce.number(),
    HYGRAPH_STAGE: z.string().min(1),
    NEXT_PORT: z.coerce.number(),
    NEXT_HOST: z.string().min(1),
    NEXTAUTH_URL: z.string().url(),
    NEXTAUTH_SECRET: z.string().min(1),
    TOKEN_LIFE_TIME: z.string().min(1),
    THIRDWEB_MASTER_ADDRESS: z.string().min(1),
    THIRDWEB_MASTER_PRIVATE_KEY: z.string().min(1),
    THIRDWEB_SECRET_KEY: z.string().min(1),
    SUMSUB_API_KEY: z.string().min(1),
    SUMSUB_SECRET_KEY: z.string().min(1),
    SUMSUB_WEBHOOKS_SECRET_KEY: z.string().min(1),
    STRIPE_PUBLISHABLE_KEY: z.string().min(1),
    STRIPE_API_KEY: z.string().min(1),
    STRIPE_WEBHOOK_SECRET: z.string().min(1),
    KV_REST_API_URL: z.string().url(),
    KV_REST_API_TOKEN: z.string().min(1),
    TZ: z.string().min(1),
  },
  runtimeEnv: {
    NX_CLOUD_AUTH_TOKEN: process.env.NX_CLOUD_AUTH_TOKEN,
    NX_CACHE_DIRECTORY: process.env.NX_CACHE_DIRECTORY,
    HASURA_VERSION: process.env.HASURA_VERSION,
    HASURA_GRAPHQL_SERVER_PORT: process.env.HASURA_GRAPHQL_SERVER_PORT,
    HASURA_GRAPHQL_ADMIN_SECRET: process.env.HASURA_GRAPHQL_ADMIN_SECRET,
    HASURA_CONSOLE_PORT: process.env.HASURA_CONSOLE_PORT,
    HASURA_GRAPHQL_DATABASE_URL: process.env.HASURA_GRAPHQL_DATABASE_URL,
    HYGRAPH_CMS_WEBHOOK_READ_URL: process.env.HYGRAPH_CMS_WEBHOOK_READ_URL,
    HASURA_GRAPHQL_UNAUTHORIZED_ROLE:
      process.env.HASURA_GRAPHQL_UNAUTHORIZED_ROLE,
    POSTGRES_USER: process.env.POSTGRES_USER,
    POSTGRES_DB: process.env.POSTGRES_DB,
    POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
    POSTGRES_PORT: process.env.POSTGRES_PORT,
    HYGRAPH_STAGE: process.env.HYGRAPH_STAGE,
    NEXT_PORT: process.env.NEXT_PORT,
    NEXT_HOST: process.env.NEXT_HOST,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    TOKEN_LIFE_TIME: process.env.TOKEN_LIFE_TIME,
    THIRDWEB_MASTER_ADDRESS: process.env.THIRDWEB_MASTER_ADDRESS,
    THIRDWEB_MASTER_PRIVATE_KEY: process.env.THIRDWEB_MASTER_PRIVATE_KEY,
    THIRDWEB_SECRET_KEY: process.env.THIRDWEB_SECRET_KEY,
    SUMSUB_API_KEY: process.env.SUMSUB_API_KEY,
    SUMSUB_SECRET_KEY: process.env.SUMSUB_SECRET_KEY,
    SUMSUB_WEBHOOKS_SECRET_KEY: process.env.SUMSUB_WEBHOOKS_SECRET_KEY,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_API_KEY: process.env.STRIPE_API_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    KV_REST_API_URL: process.env.KV_REST_API_URL,
    KV_REST_API_TOKEN: process.env.KV_REST_API_TOKEN,
    TZ: process.env.TZ,
  },
});

export default env;
