query GetEventWithPasses($slug: String!, $locale: Locale!, $stage: Stage!) {
  event(where: { slug: $slug }, locales: [$locale, en], stage: $stage) {
    id
    slug
    title
    heroImage {
      url
    }
    organizer {
      id
      slug
      name
      image {
        url
      }
    }
    eventPasses {
      id
      name
      description
      price {
        amount
        currency
      }
    }
  }
}
