query GetEventPassOrderForEventPasses($eventPassIds: [String!]) {
  eventPassOrder(where: { eventPassId: { _in: $eventPassIds } }) {
    id
    eventPassId
    quantity
    status
    created_at
    updated_at
  }
}

mutation InsertEventPassPendingOrders(
  $objects: [eventPassPendingOrder_insert_input!]!
) {
  insert_eventPassPendingOrder(objects: $objects) {
    returning {
      id
      quantity
      eventPassId
      created_at
    }
  }
}

mutation DeleteEventPassOrder($eventPassOrderId: uuid!) {
  delete_eventPassPendingOrder_by_pk(id: $eventPassOrderId) {
    id
  }
}
