query GetShopifyCustomer($organizerId: String!, $customerId: String!) @cached {
  shopifyCustomer(
    where: {
      organizerId: { _eq: $organizerId }
      customerId: { _eq: $customerId }
    }
    limit: 1
  ) {
    address
  }
}
