query GetShopifyCustomer($organizerId: String!, $customerId: String!) {
  shopifyCustomer(
    where: {
      organizerId: { _eq: $organizerId }
      customerId: { _eq: $customerId }
    }
    limit: 1
  ) {
    address
  }
}

query GetShopifyCustomers($organizerId: String!, $customerIds: [String!]!) {
  shopifyCustomer(
    where: {
      organizerId: { _eq: $organizerId }
      customerId: { _in: $customerIds }
    }
  ) {
    address
  }
}
