mutation CreateStripeCheckoutSession(
  $stripeCheckoutSession: stripeCheckoutSession_insert_input!
) {
  insert_stripeCheckoutSession_one(object: $stripeCheckoutSession) {
    ...StripeCheckoutSessionFields
  }
}

mutation DeleteStripeCheckoutSession($stripeSessionId: String!) {
  delete_stripeCheckoutSession_by_pk(stripeSessionId: $stripeSessionId) {
    ...StripeCheckoutSessionFields
  }
}
