mutation CreateStripeCustomer($stripeCustomer: stripeCustomer_insert_input!) {
  insert_stripeCustomer_one(object: $stripeCustomer) {
    ...StripeCustomerFields
  }
}

mutation UpdateStripeCustomer(
  $stripeCustomerId: String!
  $stripeCustomer: stripeCustomer_set_input!
) {
  update_stripeCustomer_by_pk(
    pk_columns: { stripeCustomerId: $stripeCustomerId }
    _set: $stripeCustomer
  ) {
    ...StripeCustomerFields
  }
}
