query GetStripeCheckoutSessionForUser($stripeCustomerId: String!) {
  stripeCheckoutSession(
    where: { stripeCustomerId: { _eq: $stripeCustomerId } }
  ) {
    ...StripeCheckoutSessionFields
  }
}
