query GetNftMintPasswordsForContract(
  $contractAddress: String!
  $chainId: String!
) @cached {
  nftMintPassword(
    where: {
      contractAddress: { _eq: $contractAddress }
      chainId: { _eq: $chainId }
    }
  ) {
    password
    minterAddress
    created_at
    updated_at
  }
}

query GetNftMintPasswordsForContractAvailable(
  $contractAddress: String!
  $chainId: String!
  $organizerId: String!
) {
  nftMintPassword(
    where: {
      contractAddress: { _eq: $contractAddress }
      chainId: { _eq: $chainId }
      minterAddress: { _is_null: true }
      organizerId: { _eq: $organizerId }
    }
  ) {
    id
    password
  }
}
