query GetRoleMinimal(
  $accountId: uuid!
  $role: roles_enum!
  $organizerId: String!
  $eventId: String
) {
  roleAssignments(
    where: {
      accountId: { _eq: $accountId }
      role: { _eq: $role }
      organizerId: { _eq: $organizerId }
      eventId: { _eq: $eventId }
    }
  ) {
    id
  }
}
