query GetMyRoles {
  roleAssignments {
    ...RoleAssignmentsFields
  }
}

query GetMyRolesWithOrganizerInfos($stage: Stage!) {
  roleAssignments {
    ...RoleAssignmentsFields
    organizer(where: {}, locales: [en], stage: $stage) {
      ...OrganizerFields
    }
  }
}

query GetMyRolesWithOrganizerAndInviterInfos($stage: Stage!) {
  roleAssignments {
    ...RoleAssignmentsFields
    organizer(where: {}, locales: [en], stage: $stage) {
      ...OrganizerFields
    }
    inviter {
      address
      email
    }
  }
}
