query GetAccount($address: String!) {
  account(where: { address: { _eq: $address } }, limit: 1) {
    ...AccountFields
    kyc {
      ...KycFields
    }
    roles {
      ...RoleAssignmentFields
    }
  }
}

query GetAccountByAddress($address: String!) {
  account(where: { address: { _eq: $address } }, limit: 1) {
    ...AccountFields
  }
}

query GetAccountById($id: uuid!) {
  account(where: { id: { _eq: $id } }) {
    address
  }
}
