name: 'Chromatic Web'

on:
  pull_request:
    paths:
      - libs/ui/**
      - apps/web/**
  push:
    branches: ['main']
    paths:
      - libs/ui/**
      - apps/web/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment and cache dependencies
        uses: sebpalluel/ci/.github/actions/setup-environment@latest

      - name: Install Libvips
        run: sudo apt-get update && sudo apt-get install -y libvips-dev

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_WEB_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          onlyChanged: true
          buildScriptName: build-storybook:web

  test-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up environment and cache dependencies
        uses: sebpalluel/ci/.github/actions/setup-environment@latest

      - name: Run Storybook
        run: pnpm nx run web:storybook -- --ci --port 4401 --quiet &

      - name: Run Test-Storybook
        run: |
          pnpm install -g wait-on
          pnpm wait-on tcp:4401
          pnpm nx run web:test-storybook
