name: CI

on:
  pull_request:
  push:
    branches: ['main', 'staging']
  workflow_dispatch:

env:
  CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
  NODE_OPTIONS: '--max_old_space_size=4096'
  NX_CLOUD_AUTH_TOKEN: MTIzMmRkZjctM2RjOS00OTRkLWE0ODgtYjIyNzk1ZjlkZTFmfHJlYWQtd3JpdGU=

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: sebpalluel/ci/.github/workflows/nx-cloud-main.yml@latest
    secrets:
      ENV_FILE: ${{ secrets.ENV_FILE }}
      NX_CLOUD_AUTH_TOKEN: MTIzMmRkZjctM2RjOS00OTRkLWE0ODgtYjIyNzk1ZjlkZTFmfHJlYWQtd3JpdGU=
    with:
      runs-on: ubuntu-latest
      node-version: 20
      pnpm-version: 7
      environment: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'preview' }}
      init-commands: |
        pnpm exec nx-cloud record -- pnpm docker:test

      parallel-commands: |
        pnpm nx format:check --verbose
        pnpm nx affected --target=test-integration --parallel=false --ci --code-coverage
        # TODO put in a separate job executed manually in order to be allowed to merge on staging
        # pnpm nx affected --target=e2e --skipInstall
      parallel-commands-on-agents: |
        pnpm affected:parallel-ci
  agents:
    name: Nx Cloud - Agents
    uses: sebpalluel/ci/.github/workflows/nx-cloud-agents.yml@latest
    secrets:
      ENV_FILE: ${{ secrets.ENV_FILE }}
      NX_CLOUD_AUTH_TOKEN: MTIzMmRkZjctM2RjOS00OTRkLWE0ODgtYjIyNzk1ZjlkZTFmfHJlYWQtd3JpdGU=
    with:
      runs-on: ubuntu-latest
      environment: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'preview' }}
      node-version: 20
      pnpm-version: 7
      number-of-agents: 3
      # init-commands: |
      #   pnpm prisma generate
