name: CI

on:
  pull_request:
  push:
    branches: ['main', 'staging']
  workflow_dispatch:

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'preview' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/checkout@v3
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for nx affected commands
        id: nx
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: staging

      - name: Set up environment and cache dependencies
        uses: sebpalluel/ci/.github/actions/setup-environment@latest

      - name: Setup docker tests containers and run check 'format', 'lint', 'test'
        run: |
          pnpm docker:test
          pnpm nx format:check --verbose
          # Prefered to run sequentially because otherwise slower with vercel cache hanging
          pnpm nx affected:lint --parallel --maxParallel=3 && pnpm nx affected:test --parallel --maxParallel=3

      - name: Run integration tests
        run: |
          pnpm affected:test-integration
