name: CI

on:
  pull_request:
  push:
    branches: ['main', 'staging']
  workflow_dispatch:

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'preview' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up environment and cache dependencies
        uses: sebpalluel/ci/.github/actions/setup-environment@latest

      - name: Setup docker tests containers and run check 'format', 'lint', 'test'
        run: |
          pnpm docker:test
          pnpm nx format:check --verbose
          pnpm affected:parallel-ci

      - name: Run integration tests
        run: |
          pnpm affected:test-integration
