name: CI

on:
  pull_request:
  push:
    branches: ['main', 'staging']
  workflow_dispatch:

env:
  CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
  NODE_OPTIONS: '--max_old_space_size=4096'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: sebpalluel/ci/.github/workflows/nx-cloud-main.yml@latest
    secrets:
      ENV_FILE: ${{ secrets.ENV_FILE }}
    with:
      runs-on: ubuntu-latest
      artifacts-path: |
        dist/cypress
      artifacts-name: cypress
      environment-variables: |
        CYPRESS_CACHE_FOLDER=~/.cache/Cypress
      cypress_cache_path: ~/.cache/Cypress
      node-version: 20
      pnpm-version: 7
      environment: staging
      init-commands: |
        pnpm exec nx-cloud record -- pnpm docker:test & pnpm docker:services

      parallel-commands: |
        pnpm nx format:check --verbose
        ## test relying in prisma + hasura not working in parallel, docker services not available ?
        # pnpm nx affected --target=test-prisma --ci --code-coverage
        pnpm nx affected --target=test-integration --parallel=false --ci --code-coverage
        ## TODO set back when cypress upgraded to webpack 5, compilation error with this code `headers['Cookie'] = cookies().toString()`;
        # pnpm nx affected --target=e2e --no-watch
      parallel-commands-on-agents: |
        pnpm affected:parallel-ci
  agents:
    name: Nx Cloud - Agents
    uses: sebpalluel/ci/.github/workflows/nx-cloud-agents.yml@latest
    secrets:
      ENV_FILE: ${{ secrets.ENV_FILE }}
    with:
      runs-on: ubuntu-latest
      environment: staging
      node-version: 20
      pnpm-version: 7
      number-of-agents: 3
      # init-commands: |
      #   pnpm prisma generate
