name: E2E tests Web

on:
  pull_request:
    paths:
      - libs/ui/**
      - libs/features/**
      - '!libs/features/back-office/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.ref }}

      - name: Set up environment and cache dependencies
        uses: sebpalluel/ci/.github/actions/setup-environment@latest

      - name: Launch docker services
        run: pnpm docker:services & pnpm nx run web:build:production

      - name: Run e2e tests
        run: pnpm nx run web:e2e --skipInstall
