name: Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  generate-static-site:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs pnpm install and then builds it using tsc (typescript compiler)
      - uses: creepinson/pnpm-action@master
        with:
          arguments: '["nx-graph-static"]'
  deploy:
    needs: generate-static-site
    environment:
      name: Nx Graph Page
      url: https://sebpalluel.github.io/web3-monorepo-boilerplate.github.io/nx-graph/
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nx Graph Page
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './static/nx-graph'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
