name: Deploy preview apps

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Get PR sha
        id: get_pull_request_sha
        run: |
          pull_request_sha=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH" | cut -c1-8)
          echo "PULL_REQUEST_SHA=$pull_request_sha" >> $GITHUB_ENV

      - name: Neon Database Create Branch Action
        uses: neondatabase/create-branch-action@v3
        id: create_branch
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{ env.PULL_REQUEST_SHA }}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{ secrets.PG_USERNAME }}
          password: ${{ secrets.PG_PASSWORD }}

      # - name: Create Hasura Cloud preview app
      #   id: hasura_cloud_preview
      #   uses: hasura/hasura-cloud-preview-apps@v0.1.10
      #   with:
      #     name: 'marketplace-${{github.event.number}}'
      #     hasuraProjectDirectoryPath: ./hasura/app
      #     region: us-west-1
      #     tier: cloud_free
      #     hasuraEnv: |
      #       HASURA_GRAPHQL_CORS_DOMAINS=*
      #       HASURA_GRAPHQL_DATABASE_URL=${{steps.create_branch.outputs.db_url}}/neondb
      #       PG_DATABASE_URL=${{steps.create_branch.outputs.db_url}}/neondb
      #       HYGRAPH_CMS_WEBHOOK_READ_URL=${{secrets.HYGRAPH_CMS_WEBHOOK_READ_URL}}
      #       HYGRAPH_CMS_READ_TOKEN=${{secrets.HYGRAPH_CMS_READ_TOKEN}}
      #       HASURA_GRAPHQL_UNAUTHORIZED_ROLE=anonymous
      #       HASURA_GRAPHQL_ADMIN_SECRET=${{secrets.HASURA_GRAPHQL_ADMIN_SECRET}}
      #       HASURA_GRAPHQL_JWT_SECRET=${{secrets.HASURA_GRAPHQL_JWT_SECRET}}

      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #     HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}

      # - name: Set Hasura GraphQL endpoint to .env
      #   run: |
      #     echo HASURA_PROJECT_ENDPOINT=${{steps.hasura_cloud_preview.outputs.graphQLEndpoint}} >> .env
      #     echo NEXT_PUBLIC_HASURA_PROJECT_ENDPOINT=${{steps.hasura_cloud_preview.outputs.graphQLEndpoint}} >> .env

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ['web', 'back-office']
    env:
      VERCEL_PROJECT_ID: ${{ matrix.app == 'web' && secrets.VERCEL_PROJECT_ID_WEB || secrets.VERCEL_PROJECT_ID_BACK_OFFICE }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up environment and cache dependencies
        uses: sebpalluel/ci/.github/actions/setup-environment@latest

      - name: Cache Vercel CLI
        uses: actions/cache@v2
        id: cache-vercel
        with:
          path: ~/.pnpm # adjust this path if needed
          key: vercel-${{ runner.os }}

      - name: Install Vercel CLI
        run: |
          if [ -z "$(npm list -g --depth=0 | grep vercel)" ]
          then
            npm install --global vercel@latest
          fi

      - name: Check if app should be built
        id: app_check_build
        run: |
          output=$(npx --y nx-ignore ${{ matrix.app }}) || true
          if [[ "$output" == *"✅ - Build can proceed"* ]]; then
            echo "BUILD_REQUIRED_${{ matrix.app }}=true" >> $GITHUB_ENV
          else
            echo "BUILD_REQUIRED_${{ matrix.app }}=false" >> $GITHUB_ENV
          fi

      - name: Deploy Preview to Vercel
        id: deploy_vercel
        env:
          BUILD_REQUIRED: ${{ env[format('BUILD_REQUIRED_{0}', matrix.app)] }}
        run: |
          if [[ $BUILD_REQUIRED == true ]]; then
            vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --local-config=apps/${{ matrix.app }}/vercel.json
            # TODO remove this when Hasura correctly deployed, was temporary to fix missing env issue
            echo HASURA_PROJECT_ENDPOINT=https://www.hasura.staging.offline.live/ >> .vercel/.env.preview.local
            echo NEXT_PUBLIC_HASURA_PROJECT_ENDPOINT=https://www.hasura.staging.offline.live/ >> .vercel/.env.preview.local
            echo NEXTAUTH_URL=https://www.preview.offline.live/ >> .vercel/.env.preview.local
            #
            vercel build --token=${{ secrets.VERCEL_TOKEN }} --local-config=apps/${{ matrix.app }}/vercel.json
            preview_url=$(vercel deploy -e HASURA_PROJECT_ENDPOINT=https://www.hasura.staging.offline.live/ -e NEXT_PUBLIC_HASURA_PROJECT_ENDPOINT=https://www.hasura.staging.offline.live  -e NEXTAUTH_URL=https://www.preview.offline.live/ --token=${{secrets.VERCEL_TOKEN}} --prebuilt --local-config=apps/${{ matrix.app }}/vercel.json --global-config=.vercel)
            echo "PREVIEW_URL_${{ matrix.app }}=$preview_url" >> $GITHUB_ENV
          else
            echo "Build not required - skipping Deploy Preview to Vercel"
          fi
  comment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: >-
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{secrets.NEON_PROJECT_ID}}/branches/${{steps.create_branch.outputs.branch_id}}
            Hasura Console :computer: : ${{steps.hasura_cloud_preview.outputs.consoleURL}}
            ${{ env.PREVIEW_URL_web != '' && format('Vercel Preview URL for Marketplace :rocket: : {0}', env.PREVIEW_URL_web) || '' }}
            ${{ env.PREVIEW_URL_back-office != '' && format('Vercel Preview URL for Back-Office :rocket: : {0}', env.PREVIEW_URL_back-office) || '' }}
