name: Deploy staging apps

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ['web', 'back-office']
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ matrix.app == 'web' && secrets.VERCEL_PROJECT_ID_WEB || secrets.VERCEL_PROJECT_ID_BACK_OFFICE }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment and cache dependencies
        uses: sebpalluel/ci/.github/actions/setup-environment@latest

      - name: Cache Vercel CLI
        uses: actions/cache@v2
        id: cache-vercel
        with:
          path: ~/.pnpm # adjust this path if needed
          key: vercel-${{ runner.os }}

      - name: Install Vercel CLI
        run: |
          if [ -z "$(npm list -g --depth=0 | grep vercel)" ]
          then
            npm install --global vercel@latest
          fi

      - name: Check if app should be built
        id: app_check_build
        run: |
          output=$(npx --y nx-ignore ${{ matrix.app }}) || true
          if [[ "$output" == *"✅ - Build can proceed"* ]]; then
            echo "BUILD_REQUIRED_${{ matrix.app }}=true" >> $GITHUB_ENV
          else
            echo "BUILD_REQUIRED_${{ matrix.app }}=false" >> $GITHUB_ENV
          fi

      - name: App // Vercel Environment Information and Deploy Staging to Vercel
        env:
          BUILD_REQUIRED: ${{ env[format('BUILD_REQUIRED_{0}', matrix.app)] }}
        run: |
          if [[ $BUILD_REQUIRED == true ]]; then
            vercel pull --yes --environment=preview --git-branch=staging --token=${{ secrets.VERCEL_TOKEN }} --local-config=apps/${{ matrix.app }}/vercel.json &&
            vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --local-config=apps/${{ matrix.app }}/vercel.json
          else
            echo "Build not required - skipping Vercel Environment Information and Deploy Staging to Vercel"
          fi
